name: Test

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:
    name: OTP ${{ matrix.otp_version }} / rebar3 ${{ matrix.rebar3_version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - otp_version: "24"
            rebar3_version: "3.21.0"
            os: ubuntu-latest
          - otp_version: "25"
            rebar3_version: "3.21.0"
            os: ubuntu-latest
          - otp_version: "26"
            rebar3_version: "3.25.1"
            os: ubuntu-latest
          - otp_version: "27"
            rebar3_version: "3.25.1"
            os: ubuntu-latest
          - otp_version: "28"
            rebar3_version: "3.25.1"
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: ${{ matrix.rebar3_version }}

    - uses: actions/cache@v4
      name: Cache
      with:
        path: |
          _build
        key: ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ matrix.rebar3_version }}-${{ hashFiles(format('rebar.lock')) }}-1
        restore-keys: |
          ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ matrix.rebar3_version }}-1-

    - name: Report
      run: rebar3 report "compile"

    - name: Compile
      run: rebar3 compile

    - name: Common Test tests
      run: rebar3 ct --cover

    - name: XRef
      run: rebar3 xref

    - name: Dialyzer
      run: rebar3 dialyzer
      if: ${{ matrix.otp_version == 28 }}
